export interface WhatsAppTemplateComponent {
  type: 'HEADER' | 'BODY' | 'FOOTER' | 'BUTTONS';
  format?: 'TEXT' | 'IMAGE' | 'VIDEO' | 'DOCUMENT';
  text?: string;
  example?: {
    header_text?: string[];
    body_text?: string[][];
  };
  buttons?: Array<{
    type: 'QUICK_REPLY' | 'URL' | 'PHONE_NUMBER';
    text: string;
    url?: string;
    phone_number?: string;
  }>;
}

export interface WhatsAppTemplateDefinition {
  name: string;
  category: 'UTILITY' | 'MARKETING' | 'AUTHENTICATION';
  language: string;
  components: WhatsAppTemplateComponent[];
  description?: string;
}

const whatsappTemplates: Record<string, WhatsAppTemplateDefinition> = {
  daily_kpi_snapshot: {
    name: 'daily_kpi_snapshot',
    category: 'UTILITY',
    language: 'en',
    description: 'Daily KPI snapshot report template',
    components: [
      {
        type: 'HEADER',
        format: 'TEXT',
        text: 'Daily KPI Snapshot',
        example: {
          header_text: ['Daily KPI Snapshot']
        }
      },
      {
        type: 'BODY',
        text: 'Store: {{1}}\nDate: {{2}}\n\n{{3}}\n\n{{4}}\n\n{{5}}\n\n{{6}}',
        example: {
          body_text: [
            ['My Store', '2024-01-15', 'Business Overview: Sales up 20%', 'Marketing: ROI 150%', 'Operations: Cash flow positive', 'Signals: All systems operational']
          ]
        }
      },
      {
        type: 'FOOTER',
        text: 'Generated by Netsight'
      }
    ]
  },
  order_confirmation: {
    name: 'order_confirmation',
    category: 'UTILITY',
    language: 'en',
    description: 'Order confirmation template',
    components: [
      {
        type: 'BODY',
        text: 'Hello {{1}},\n\nYour order {{2}} has been confirmed!\n\nOrder Date: {{3}}\nTotal Amount: {{4}}\n\nThank you for your purchase!',
        example: {
          body_text: [
            ['John Doe', 'ORD-12345', '2024-01-15', '$99.99']
          ]
        }
      }
    ]
  },
  custom_notification: {
    name: 'custom_notification',
    category: 'UTILITY',
    language: 'en',
    description: 'Custom notification template',
    components: [
      {
        type: 'BODY',
        text: '{{1}}\n\n{{2}}',
        example: {
          body_text: [
            ['Important Update', 'Your account has been updated successfully.']
          ]
        }
      }
    ]
  }
};

export function getWhatsAppTemplate(templateName: string): WhatsAppTemplateDefinition | null {
  return whatsappTemplates[templateName] || null;
}

export function getAllWhatsAppTemplates(): Record<string, WhatsAppTemplateDefinition> {
  return whatsappTemplates;
}

export function registerWhatsAppTemplate(template: WhatsAppTemplateDefinition): void {
  whatsappTemplates[template.name] = template;
}

export default {
  getWhatsAppTemplate,
  getAllWhatsAppTemplates,
  registerWhatsAppTemplate
};
